---
title: Is the No Free Lunch Theorem (NFL) relevant in practice?
---
_The BBOBies, November 2025 (3 minutes read with footnotes)_

The short answer is "_no_"!

The No Free Lunch Theorem (NFL) states that aggregated over all functions, _all search algorithms perform identical_, given they do not revisit solutions [@wolpert2002no].
This is true if (and only if) the set of functions is closed under permutation [@schumacher2001no].

Trying to differentiate algorithms by means of benchmarking can only be meaningful if NFL does _not_ hold on the set (or weighted set)[^weighting] of functions of interest.

Let us consider the set of all (possible) functions $R^n\to R$ _discretized with two bytes_ per real number[^discretenote] and call this set $F_n$.
The No Free Lunch Theorem holds for this set of functions _because the set is closed under permutation._
The number of functions in $F_n$ is[^funnumber]

$$|F_n| = \left(2^{16}\right)^{\left(2^{16}\right)^n}
        = 2^{16\times 2^{16n}}
        > 10^{4.8 \times 10^{4.8n}}
        > 10^{5\times 50000^{n}}$$

Let us put the size of $F_n$ into perspective.
The number of electrons in the universe multiplied by the number of Planck times passed since the beginning of time is about $10^{141}$.[^planck]
This number is minuscule compared to $|F_n|>10^{5\times 50000^{n}}$.
Hence, the number of real world functions we could _possibly ever encounter_ (and hence _could_ possibly be relevant to us) **is a minuscule subclass of _all_ problems** and hence NFL (in general) does not hold.[^subset]

Could NFL hold for _any_ practically relevant set of continuous (discretized) functions?
We don't know for certain,[^knowing] but it looks _exceedingly_ unlikely to us.


[^discretenote]: As an example, this gives roughly 5 digits of precision for representing numbers from the interval $[0,1]$.
  In some practical situations we may require more precision or a wider range.
  Hence, the following size derivation is on the conservative side.

[^planck]: The number of electrons (or atoms) in the universe is about $10^{80}$.
  The age of the universe is about $10^{18}$ seconds.
  The Planck time is about $10^{-43}$ seconds.
  The number of all electrons in the universe multiplied by the number of Planck times since the beginning of the universe is hence about $10^{80} \times 10^{61} = 10^{141}.$

[^funnumber]: The number of functions equals the number of different function values to the power of the number of different solutions. The smallest nontrivial subsets of $F_n$ in which NFL holds are $(2^{16})^n \approx 10^{4.8n}$ needles-in-the-flat functions. NFL never holds on any single function which has at least two different $f$-values.

[^knowing]: Given any observable set of nontrivial "continuous" _real world_ problems, it seems hard to conceive how we could determine that NFL holds for this set. The existence of algorithms that do perform differently seems however easy to establish if we could sample (uniformly) from the problem class.

[^subset]: In general, _any_ function subset is highly unlikely to obey NFL and any nontrivial neighbourhood is not invariant under permutation [@igel2005no].
Furthermore, we would expect different functions to have different importance weights (probabilities).


[^weighting]: For the time being, we assume, somewhat unrealistically, equal frequency and/or equal importance weight for all functions.

<!--
Wolpert, D.H. and Macready, W.G., 2002. No free lunch theorems for optimization. _IEEE transactions on evolutionary computation,_ 1(1), pp.67-82
Igel, C. and Toussaint, M., 2005. A no-free-lunch theorem for non-uniform distributions of target functions. _Journal of Mathematical Modelling and Algorithms,_ 3(4), pp.313-322.
-->
