project:
  type: website
  output-dir: _site
  preview:
    port: 4204
    browser: false
  resources: 
    - env.yaml
    - "*.ipynb"
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!scripts/"
    - "!README.md"
    - "env.yaml"

bibliography: references.bib
csl: style.csl
lang: en

website:
  title: "<b>CO</b>mparing <b>C</b>ontinuous <b>O</b>ptimizers"
  open-graph: true  
  sidebar:    
    logo: assets/images/coco-logo.svg
    style: floating
    search: true
    collapse-level: 2
    contents:
    - text: "Home"
      href: index.qmd
    - text: "Get Started"
      href: getting-started/index.qmd
    - section: Test Suites
      contents:
        - section: bbob
          contents:
            - text: Overview
            - text: Problem Visualizations
            - section: Function Definitions
              contents:
                - text: f<sub>1</sub> - Sphere
                - text: f<sub>2</sub> - Separable Ellipsoid
                - text: f<sub>3</sub> - Separable Rastrigin
                - text: f<sub>4</sub> - Büche-Rastrigin
                - text: f<sub>5</sub> - Linear Slope
                - text: f<sub>6</sub> - Attractive Sector
                - text: f<sub>7</sub> - Step Ellipsoid
                - text: f<sub>8</sub> - Rosenbrock (original)
                - text: f<sub>9</sub> - Rosenbrock (rotated)
                - text: f<sub>10</sub> - Ellipsoid
                - text: f<sub>11</sub> - Discus
                - text: f<sub>12</sub> - Bent Cigar
                - text: f<sub>13</sub> - Sharp Ridge
                - text: f<sub>14</sub> - Different Powers
                - text: f<sub>15</sub> - Rastrigin
                - text: f<sub>16</sub> - Weierstrass
                - text: f<sub>17</sub> - Schaffer's F7
                - text: f<sub>18</sub> - Schaffer's F7 (ill c.)
                - text: f<sub>19</sub> - Griewank-Rosenbrock
                - text: f<sub>20</sub> - Schwefel
                - text: f<sub>21</sub> - Gallagher's 101 Peaks
                - text: f<sub>22</sub> - Gallagher's 21 Peaks
                - text: f<sub>23</sub> - Katsuura
                - text: f<sub>24</sub> - Lunacek bi-Rastrigin
            - text: Performance Comparison
            - text: Data Archive
              href: data-archive/bbob.qmd
        - section: bbob-biobj  
          contents:
            - text: Data Archive
              href: data-archive/bbob-biobj.qmd
        - section: bbob-biobj-mixint
        - section: bbob-boxed
          contents:
            - text: Data Archive
              href: data-archive/bbob-boxed.qmd
        - section: bbob-constrained
          contents:
            - text: Data Archive
              href: data-archive/bbob-constrained.qmd
        - section: bbob-largescale
          contents:
            - text: Data Archive
              href: data-archive/bbob-largescale.qmd
        - section: bbob-mixint
          contents:
            - text: Data Archive
              href: data-archive/bbob-mixint.qmd
        - section: bbob-noisy
          contents:
            - text: Data Archive
              href: data-archive/bbob-noisy.qmd
    - text: "Publish Results"
      href: howto-publish.qmd
    - section: Reference
      contents:
        - text: cocopp Python API
        - text: cocoex Python API
        - text: Core cocoex C API
    - text: "Workshops"
      href: https://numbbo.github.io/workshops/
    - section: Development
      contents:
        - text: coco-experiment
        - text: coco-postprocess
        - text: coco-viz
  page-footer:
    center:
      - imprint.qmd
  search:
    type: textbox    

format:
  html:
    toc: true
    theme: coco.scss
    html-math-method: katex
    code-copy: true
    code-overflow: wrap
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
    include-in-header:
      text: |
        <link rel="icon" type="image/png" href="/assets/images/coco-logo-16.png" sizes="16x16">
        <link rel="icon" type="image/png" href="/assets/images/coco-logo-32.png" sizes="32x32">
        <link rel="icon" type="image/svg+xml" href="/assets/images/coco-logo.svg">