project:
  type: website
  output-dir: _site
  preview:
    port: 4204
    browser: false
  resources: 
    - env.yaml
    - "*.ipynb"
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!scripts/"
    - "!README.md"
    - "env.yaml"

bibliography: references.bib
csl: style.csl
lang: en

website:
  title: "<b>CO</b>mparing <b>C</b>ontinuous <b>O</b>ptimizers"
  open-graph: true  
  sidebar:    
    logo: assets/images/coco-logo.svg
    style: floating
    search: true
    collapse-level: 2
    contents:
    - text: Home
      href: index.qmd
    - text: Get Started
      href: getting-started/index.qmd
      contents:
        - text: Experiment
          href: getting-started/index.qmd#experiment
        - text: Postprocess or Display
          href: getting-started/index.qmd#postprocess
    - section: Test Suites
      contents:
      - section: bbob
        href: testsuites/bbob/overview.qmd
        contents:
          - text: Problem Visualizations
            href: testsuites/bbob/viz.qmd
          - section: Function Definitions
            contents:
              - href: testsuites/bbob/functions/f01.qmd
              - href: testsuites/bbob/functions/f02.qmd
              - href: testsuites/bbob/functions/f03.qmd
              - href: testsuites/bbob/functions/f04.qmd
              - href: testsuites/bbob/functions/f05.qmd
              - href: testsuites/bbob/functions/f06.qmd
              - href: testsuites/bbob/functions/f07.qmd
              - href: testsuites/bbob/functions/f08.qmd
              - href: testsuites/bbob/functions/f09.qmd
              - href: testsuites/bbob/functions/f10.qmd
              - href: testsuites/bbob/functions/f11.qmd
              - href: testsuites/bbob/functions/f12.qmd
              - href: testsuites/bbob/functions/f13.qmd
              - href: testsuites/bbob/functions/f14.qmd
              - href: testsuites/bbob/functions/f15.qmd
              - href: testsuites/bbob/functions/f16.qmd
              - href: testsuites/bbob/functions/f17.qmd
              - href: testsuites/bbob/functions/f18.qmd
              - href: testsuites/bbob/functions/f19.qmd
              - href: testsuites/bbob/functions/f20.qmd
              - href: testsuites/bbob/functions/f21.qmd
              - href: testsuites/bbob/functions/f22.qmd
              - href: testsuites/bbob/functions/f23.qmd
              - href: testsuites/bbob/functions/f24.qmd
          - text: Performance Comparison
            href: testsuites/bbob/performancecomparisons.qmd
          - text: Data Archive
            href: testsuites/bbob/data-archive.qmd
          - text: Temporary Placement of Research Questions
            href: testsuites/bbob/rq.qmd
      - section: bbob-biobj  
        href: testsuites/bbob-biobj/overview.qmd
        contents:
          - text: Problem Visualizations
            href: testsuites/bbob-biobj/viz.qmd
          - text: Function Definitions
            href: testsuites/bbob-biobj/def.qmd
          - text: Gradient Angle Plots
            href: testsuites/bbob-biobj/ecdfs.qmd
          - text: Performance Comparison
            href: testsuites/bbob-biobj/performancecomparisons.qmd
          - text: Data Archive
            href: testsuites/bbob-biobj/data-archive.qmd
      - section: bbob-biobj-mixint
      - section: bbob-boxed
        contents:
          - text: Data Archive
            href: testsuites/bbob-boxed/data-archive.qmd
      - section: bbob-constrained
        contents:
          - text: Suite
            href: testsuites/bbob-constrained/test-suite.qmd
          - text: Data Archive
            href: testsuites/bbob-constrained/data-archive.qmd
      - section: bbob-largescale
        contents:
          - text: Suite
            href: testsuites/bbob-largescale/test-suite.qmd
          - text: Data Archive
            href: testsuites/bbob-largescale/data-archive.qmd
      - section: bbob-mixint
        contents:
          # - text: Problem Visualizations  # seem not to display the correct functions
          #   href: https://numbbo.github.io/temp-doc-bbob/bbob-mixint/vis.html
          - text: Function Definitions
            href: https://numbbo.github.io/temp-doc-bbob/bbob-mixint/def.html
          - text: Further suite information/links
            href: testsuites/bbob-mixint/test-suite.qmd
          - text: Data Archive
            href: testsuites/bbob-mixint/data-archive.qmd
      - section: bbob-noisy
        contents:
          - text: Problem Visualizations
            href: https://numbbo.github.io/temp-doc-bbob/bbob-noisy/vis.html
          - text: Function Definitions
            href: https://numbbo.github.io/temp-doc-bbob/bbob-noisy/def.html
          - text: Data Archive
            href: testsuites/bbob-noisy/data-archive.qmd
    - text: "Publish Results"
      href: howto-publish.qmd
    - section: Reference
      contents:
        - text: cocopp Python API
          href: http://numbbo.github.io/coco-doc/apidocs/cocopp
        - text: cocoex Python API
          href: http://numbbo.github.io/coco-doc/apidocs/cocoex
        - text: Core cocoex C API
          href: http://numbbo.github.io/coco-doc/C
    - text: "Workshops"
      href: https://numbbo.github.io/workshops/
    - section: Development
      contents:
        - text: coco-experiment
          href: https://github.com/numbbo/coco-experiment
        - text: coco-postprocess
          href: https://github.com/numbbo/coco-postprocess
        - text: coco-visualize
          href: https://github.com/numbbo/coco-visualize
  search:
    type: textbox    

format:
  html:
    toc: true
    theme:
      - cosmo
      - coco.scss
    html-math-method: katex
    code-copy: true
    code-overflow: wrap
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
    css: /assets/css/data-table.css
    include-in-header:      
      text: |
        <link rel="icon" type="image/png" href="/assets/images/coco-logo-16.png" sizes="16x16">
        <link rel="icon" type="image/png" href="/assets/images/coco-logo-32.png" sizes="32x32">
        <link rel="icon" type="image/svg+xml" href="/assets/images/coco-logo.svg">
        <link rel="icon" type="image/svg+xml" href="/assets/images/coco-logo.svg">
        <link rel="shortcut icon" type="image/png" href="/assets/images/coco-logo-192.png">
        <link rel="shortcut icon" sizes="192x192" href="/assets/images/coco-logo-192.png">
        <link rel="apple-touch-icon" href="/assets/images/coco-logo-192.png">
        <script defer src="https://umami.0x200.net/script.js" data-website-id="d3bf2497-9b15-4f22-829f-e54590c461aa"></script>