project:
  type: website
  output-dir: _site
  preview:
    port: 4204
    browser: false
  resources: 
    - env.yaml
    - "*.ipynb"
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!scripts/"
    - "!README.md"
    - "env.yaml"

bibliography: references.bib
csl: style.csl
lang: en

website:
  title: "<b>CO</b>mparing <b>C</b>ontinuous <b>O</b>ptimizers"
  open-graph: true  
  sidebar:    
    logo: assets/images/coco-logo.svg
    style: floating
    search: true
    collapse-level: 2
    contents:
    - text: Home
      href: index.qmd
    - text: Get Started
      href: getting-started/index.qmd
    - section: Test Suites
      contents:
      - section: "<code>bbob</code>"
        href: bbob/overview.qmd
        contents:
          - text: Problem Visualizations
            href: bbob/viz.qmd
          - section: Function Definitions
            contents:
              - href: bbob/functions/f01.qmd
              - href: bbob/functions/f02.qmd
              - href: bbob/functions/f03.qmd
              - href: bbob/functions/f04.qmd
              - href: bbob/functions/f05.qmd
              - href: bbob/functions/f06.qmd
              - href: bbob/functions/f07.qmd
              - href: bbob/functions/f08.qmd
              - href: bbob/functions/f09.qmd
              - href: bbob/functions/f10.qmd
              - href: bbob/functions/f11.qmd
              - href: bbob/functions/f12.qmd
              - href: bbob/functions/f13.qmd
              - href: bbob/functions/f14.qmd
              - href: bbob/functions/f15.qmd
              - href: bbob/functions/f16.qmd
              - href: bbob/functions/f17.qmd
              - href: bbob/functions/f18.qmd
              - href: bbob/functions/f19.qmd
              - href: bbob/functions/f20.qmd
              - href: bbob/functions/f21.qmd
              - href: bbob/functions/f22.qmd
              - href: bbob/functions/f23.qmd
              - href: bbob/functions/f24.qmd
          - text: Performance Comparison
          - text: Data Archive
            href: data-archive/bbob.qmd
      - section: bbob-biobj  
        contents:
          - text: Data Archive
            href: data-archive/bbob-biobj.qmd
      - section: bbob-biobj-mixint
      - section: bbob-boxed
        contents:
          - text: Data Archive
            href: data-archive/bbob-boxed.qmd
      - section: bbob-constrained
        contents:
          - text: Data Archive
            href: data-archive/bbob-constrained.qmd
      - section: bbob-largescale
        contents:
          - text: Data Archive
            href: data-archive/bbob-largescale.qmd
      - section: bbob-mixint
        contents:
          - text: Data Archive
            href: data-archive/bbob-mixint.qmd
      - section: bbob-noisy
        contents:
          - text: Data Archive
            href: data-archive/bbob-noisy.qmd
    - text: "Publish Results"
      href: howto-publish.qmd
    - section: Reference
      contents:
        - text: cocopp Python API
        - text: cocoex Python API
        - text: Core cocoex C API
    - text: "Workshops"
      href: https://numbbo.github.io/workshops/
    - section: Development
      contents:
        - text: coco-experiment
        - text: coco-postprocess
        - text: coco-viz
  page-footer:
    center:
      - imprint.qmd
  search:
    type: textbox    

format:
  html:
    toc: true
    #theme: coco.scss
    html-math-method: katex
    code-copy: true
    code-overflow: wrap
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
    css: /assets/css/data-table.css
    include-in-header:      
      text: |
        <link rel="icon" type="image/png" href="/assets/images/coco-logo-16.png" sizes="16x16">
        <link rel="icon" type="image/png" href="/assets/images/coco-logo-32.png" sizes="32x32">
        <link rel="icon" type="image/svg+xml" href="/assets/images/coco-logo.svg">
        <link rel="icon" type="image/svg+xml" href="/assets/images/coco-logo.svg">
        <link rel="shortcut icon" type="image/png" href="/assets/images/coco-logo-192.png">
        <link rel="shortcut icon" sizes="192x192" href="/assets/images/coco-logo-192.png">
        <link rel="apple-touch-icon" href="/assets/images/coco-logo-192.png">
        