---
title: Noisy test suite
---

There are two ways to run experiments on a noisy test suite.

1. Using the [`bbob-noisy`](https://numbbo.github.io/temp-doc-bbob/bbob-noisy/def.html) suite [@bbob2009noisy],
   `suite = cocoex.Suite('bbob-noisy', '', '')`,
   see also the [function visualizations](https://numbbo.github.io/temp-doc-bbob/bbob-noisy/vis.html).
   This suite features 30 functions, `f101`--`f130`, with three different noise models in two different magnitudes
   based on 8 of the 24 functions from the [`bbob`](testsuites/bbob/overview.qmd) test suite.
2. Using the [`cocoex.noiser.Noisifier`](https://numbbo.github.io/coco-doc/apidocs/cocoex/cocoex.noiser.Noisifier.html) (since 2025, only available in Python)
   as described in more detail in [this issue](https://github.com/numbbo/coco-experiment/issues/36).[^issue36]
   The noisifier can be used with any COCO test suite.
   The resulting data can be post-processed as usual.
   However, the post-processing does not recognize whether a noisifier was applied during the experiment.
   Hence the figures themselves won't give any hints on the applied noise parameters.

[^issue36]: [Feature description] A Noisifier for objective functions. [Issue #36](https://github.com/numbbo/coco-experiment/issues/36)
            of the [`numbbo/coco-experiment`](https://github.com/numbbo/coco-experiment) Github repository.