on:
  push:
    branches: main
  workflow_dispatch:

name: Build website

defaults:
  run:
    shell: bash -l {0}

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: env.yaml
          cache-env: true
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render
        shell: bash -l {0}
        run: quarto render
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy to host
        run: rsync --delete-after --delete-excluded --recursive _site/ gh-deploy@maans07.gm.fh-koeln.de:/var/www/numbbo.it
